---
- name: Prepare Windows
  hosts:
    - windows
  gather_facts: false
  tasks:
    - name: Remove existing Chocolatey package
      chocolatey.chocolatey.win_chocolatey:
        name: bleachbit.portable
        state: absent
